Feature/video uploading backend
vbee-holding/20211-20183609 pull request #9
Opened 2021-11-27 07:09 UTC by quanhoang288

- Add file validation
- Generate video thumbnail
- Encode video and generate chunks
- Upload generated files to google drive
- TODO:
  - Handle database storage
  - Update upload logic when receiving video's metadata (description, user restriction)

2021-11-27 09:41 UTC, minhpq-vbee requested changes
- Keeping coding no convention.
- Missing empty line at the EOF.
-

2021-11-27 09:41 UTC, minhpq-vbee commented on react-node-video-streaming/server/utils/cloudUpload.js
> +
try what?

2021-11-27 09:52 UTC, quanhoang288 commented on react-node-video-streaming/server/utils/cloudUpload.js
> +
em quên chưa cop đoạn code vào try ạ

2021-12-01 02:48 UTC, minhpq-vbee approved these changes

2021-12-01 02:48 UTC, merged